#!/bin/bash

ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_118_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_118_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_118_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_118_4.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_118_5.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_118_6.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_118_7.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_118_8.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_119_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_119_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_10.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_11.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_4.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_5.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_6.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_7.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_8.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_121_9.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_10.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_11.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_12.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_4.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_5_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_5_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_6.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_7.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_8.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_122_9.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_123_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_123_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_123_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_123_4.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_123_5.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_123_6.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_129.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_158_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_158_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_159_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_159_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_160_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_160_2_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_160_2_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_164_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_167_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_167_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_168_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_168_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_171.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_172_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_172_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_172_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_172_4.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_172_5.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_173_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_173_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_173_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_173_4.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_173_5.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_173_6.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_173_7.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_173_8.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_182.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_211.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_222.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_225.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_226.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_10.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_11.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_12.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_4.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_6.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_7.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_8.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_233_9.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_236.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_249_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_249_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_249_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_250.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_260.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_264.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_275.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_278.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_294.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_295_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_302_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_302_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_329.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_380_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_380_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_380_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_380_4.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_380_5.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_380_6.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_380_7.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_380_8.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_380_9.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_386.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_391.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_402.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_413_1.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_413_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_413_3.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_432_1_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_432_2_2.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_538.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_548.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_564.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_565.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_566.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_567.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_568.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_569.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_570.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_571.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_572.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_573.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_574.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_575.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_576.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_583.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_586.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_628.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_631.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_593.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_589.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_612.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_618.mp4
ls /Volumes/dcapspub/htdocs/kaltura/Africana/AFR_video_620.mp4
